# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.1
    environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    ports:
      - 5050:80